### ISSUE TITLE
Cannot run PyNEST/example.py

### ISSUE THREAD

**Issue by 104H** [OpenSourceBrain/PotjansDiesmann2014#9]
Running PyNEST/example.py gives the following error on Nest 3.1

```
data directory created
Data will be written to /home/pbr-student/PotjansDiesmann2014/data/
Time to initialize the network: 0.00 s
Master seed: 55 
Number of total processes: 1
Seeds for random number generators of virtual processes: [57]
Global random number generator seed: 56
Traceback (most recent call last):
  File "PyNEST/example.py", line 51, in <module>
    net.setup()
  File "/home/pbr-student/PotjansDiesmann2014/PyNEST/network.py", line 498, in setup
    self.setup_nest()
  File "/home/pbr-student/PotjansDiesmann2014/PyNEST/network.py", line 126, in setup_nest
    nest.SetKernelStatus(kernel_dict)
  File "/usr/lib/python3.8/site-packages/nest/ll_api.py", line 227, in stack_checker_func
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/nest/lib/hl_api_simulation.py", line 237, in SetKernelStatus
    raise ValueError(msg)
ValueError: `grng_seed` is not a valid kernel parameter, valid parameters are: 'T_max', 'T_min', 'adaptive_spike_buffers', 'adaptive_target_buffers', 'biological_time', 'buffer_size_secondary_events', 'buffer_size_spike_data', 'buffer_size_target_data', 'data_path', 'data_prefix', 'dict_miss_is_error', 'growth_factor_buffer_spike_data', 'growth_factor_buffer_target_data', 'keep_source_table', 'kernel_status', 'local_num_threads', 'local_spike_counter', 'max_buffer_size_spike_data', 'max_buffer_size_target_data', 'max_delay', 'max_num_syn_models', 'max_update_time', 'min_delay', 'min_update_time', 'ms_per_tic', 'network_size', 'num_connections', 'num_processes', 'off_grid_spiking', 'overwrite_files', 'print_time', 'recording_backends', 'resolution', 'rng_seed', 'rng_type', 'rng_types', 'sort_connections_by_source', 'structural_plasticity_synapses', 'structural_plasticity_update_interval', 'tics_per_ms', 'tics_per_step', 'to_do', 'total_num_virtual_procs', 'update_time_limit', 'use_compressed_spikes', 'use_wfr', 'wfr_comm_interval', 'wfr_interpolation_order', 'wfr_max_iterations', 'wfr_tol'
```

**Comment by jougs** [comment]
I seems that the model has not been updated to work with NEST 3.1, where you have to set a single `rng_seed` instead of a `grng_seed` and list of `rng_seeds`.

@pgleeson: how is the policy and who's responsible for updating [the files over here](https://github.com/OpenSourceBrain/PotjansDiesmann2014/tree/master/PyNEST) with new versions from the upstream project? Cheers!

Also, @albada, @jhnnsnk

**Comment by jhnnsnk** [comment]
I have updated the PyNEST files in PR #7 to NEST 3.1.

**Comment by pgleeson** [comment]
Thanks for reporting @104H , it does seem like this was a NEST 3.1 issue, and the updated version in PR #7 by @jhnnsnk  mentioned above should work.

@jougs Happy to merge the new version, but I've been updating the [OMV based testing framework](https://github.com/OpenSourceBrain/osb-model-validation) to support multiple version of NEST to be able to test the different versions of the network (NEST, PyNEST, PyNN etc). This is partially updated, but I still need to test the PyNN version with the latest PyNN 0.10.0 and NEST 3. 

@jhnnsnk I assume the PyNEST code wont work on NEST < 3.0?

@jougs Any of the recent NEST versions pip installable..?

**Comment by jhnnsnk** [comment]
> @jhnnsnk I assume the PyNEST code wont work on NEST < 3.0?

That's true. We have for  benchmarking purposes a version of the model that works with both NEST 2 and 3: [Potjans_2014](https://github.com/INM-6/beNNch-models/tree/main/Potjans_2014)
However, that version might be a bit cumbersome with the distinct code parts for the different NEST versions. In general, we would like to encourage people to use NEST 3.
@jougs What do you think would be the best strategy here?

**Comment by jougs** [comment]
I fully support the idea of people transitioning to NEST 3. I'd say this repository should always reflect the version of the model that is compatible with the newest version of NEST. That's also easy to document. If people need older versions, git's a version control system after all ;-) Also, we're of course always happy to help people on the mailing list, should problems arise with their transition to newer versions.

> @jougs Any of the recent NEST versions pip installable..?

Nope. Sorry! We're working on it in https://github.com/nest/nest-simulator/pull/2170, but there's still some road blocks.
